import esbuild from "esbuild"
import process from "process"
import builtins from "builtin-modules"

const banner = `/*
THIS FILE IS AUTOGENERATED
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`
const args = process.argv.slice(2)
const isWatch = args.includes("-w") || args.includes("--watch")
const isRelease = args.includes("--release")

const config = {
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts", "src/styles.css"],
    outdir: "./",
    define: {
        DFT_VERSION: JSON.stringify(process.env.DFT_RELEASE_VERSION),
        DFT_BUILD_ID: JSON.stringify(process.env.DFT_RELEASE_BUILD_ID),
        DFT_BUILD_TYPE: JSON.stringify(isRelease ? "release" : "debug"),
        DFT_CONFIG: JSON.stringify(process.env.DFT_CONFIG || null),
    },
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: isRelease ? false : "inline",
    treeShaking: true,
    minify: isRelease,
}

const context = await esbuild.context(config)

if (isWatch) {
    await context.watch()
} else {
    await context.rebuild()
    process.exit(0)
}
